services:
- type: web
  name: django-app
  env: docker
  build:
    dockerfile: Dockerfile
  startCommand:
    - gunicorn personal_portfolio.wsgi
  envVars:
  - key: DJANGO_SETTINGS_MODULE
    value: personal_portfolio.settings
  - key: SECRET_KEY
    value: mysecretkey
  - key: DEBUG
    value: 'false'
  - key: ALLOWED_HOSTS
    value: .onrender.com
