services:
- type: web
  name: django-app
  env: docker
  build:
    dockerfile: Dockerfile
  envVars:
  - key: DJANGO_SETTINGS_MODULE
    value: myapp.settings
  - key: SECRET_KEY
    value: mysecretkey
  - key: DEBUG
    value: 'false'
  - key: ALLOWED_HOSTS
    value: .onrender.com